Hman 166
hmcts/hmc-cft-hearing-service pull request #173
Opened 2022-04-29 16:45 UTC by marvincudjoe

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/HMAN-166

### Change description ###
@APIResponse uses variables from the ValidationError class.
Added a few more variables for the relevant responses 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-05-03 08:26 UTC, RebeccaBaker requested changes

2022-05-03 08:26 UTC, RebeccaBaker commented on src/main/java/uk/gov/hmcts/reform/hmc/controllers/HearingActualsManagementController.java
> +            + "\n004) " + ValidationError.HEARING_ACTUALS_NON_UNIQUE_HEARING_DAYS),
the numbering seems to be incorrect

2022-05-03 08:26 UTC, RebeccaBaker commented on src/main/java/uk/gov/hmcts/reform/hmc/controllers/LinkHearingGroupController.java
> +                + "\n005) " + ValidationError.HEARING_ORDER_NOT_UNIQUE)
can we change numbering to 1,2,3,4,5 not 001 etc

2022-05-03 08:26 UTC, RebeccaBaker commented on src/main/java/uk/gov/hmcts/reform/hmc/controllers/LinkHearingGroupController.java
> +                + "\n008) " + ValidationError.INVALID_STATE_FOR_UNLINKING_HEARING_REQUEST)
same again

2022-05-03 08:26 UTC, RebeccaBaker commented on src/main/java/uk/gov/hmcts/reform/hmc/controllers/PartiesNotifiedController.java
> +        @ApiResponse(code = 500, message = ValidationError.INTERNAL_SERVER_ERROR)
and here

2022-05-03 08:26 UTC, RebeccaBaker commented on src/main/java/uk/gov/hmcts/reform/hmc/controllers/PartiesNotifiedController.java
> +                + "\n002) " + ValidationError.PARTIES_NOTIFIED_RESPONSE_VERSION_MISMATCH)
plus this one

2022-05-03 08:26 UTC, RebeccaBaker commented on src/main/java/uk/gov/hmcts/reform/hmc/controllers/HearingActualsManagementController.java
> +        @ApiResponse(code = 200, message = ValidationError.HEARING_ACTUALS_SUCCESSFULLY_PROCESSED),
for all successful flows can they be reverted back to a string and removed from Validation.Error

2022-05-31 09:32 UTC, padmapriyanalam approved these changes

2022-05-31 14:16 UTC, merged