HMAN 228 HMAN 229 new database table hearing_channels
hmcts/hmc-cft-hearing-service pull request #215
Opened 2022-06-01 10:32 UTC by marvincudjoe

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/HMAN-229
https://tools.hmcts.net/jira/browse/HMAN-229

### Change description ###
New database table hearing_channels
Endpoints updated to allow new element channelType
- POST /hearing and PUT /hearing 
- GET /hearing and /hearings

**Does this PR introduce a breaking change?** (check one with "x")

```
[ x] Yes - hearingChannels is required in the payload
[ ] No
```

2022-06-09 10:10 UTC, markdathornehmcts commented on src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseMapperTest.java
>      void toHearingsResponseWhenRequestIdIsNull() {
Where is the @Test for this method now?

2022-06-09 10:14 UTC, markdathornehmcts commented on src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseMapperTest.java
>      void toHearingsResponseWhenRequestIdIsNull() {
Re-add "@Test" to this test method

2022-06-09 10:19 UTC, markdathornehmcts requested changes
All good to me barring the 1 missing @Test annotation. Add that and if the pipeline builds successfully then approval will follow

2022-06-09 14:34 UTC, RebeccaBaker commented on src/main/java/uk/gov/hmcts/reform/hmc/model/hmi/Listing.java
> +    private List<HearingChannel> listingHearingChannels;
same comment as above

2022-06-09 14:48 UTC, RebeccaBaker commented on src/main/java/uk/gov/hmcts/reform/hmc/model/HearingDetails.java
> +    private List<HearingChannel> hearingChannels;
same comment as above

2022-06-10 13:58 UTC, RebeccaBaker commented on src/main/java/uk/gov/hmcts/reform/hmc/model/CaseHearing.java
> +    private List<String> hearingChannels;
Is this correct, only allow 70 items in the list?

2022-06-10 13:59 UTC, RebeccaBaker approved these changes
Approved with a minor comment

2022-06-10 14:23 UTC, markdathornehmcts approved these changes

2022-06-24 09:53 UTC, merged